// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniEmu.Data;

#nullable disable

namespace UniEmu.Data.Migrations
{
    [DbContext(typeof(UniEmuDbContext))]
    [Migration("20260523143615_SharedResourcePartialUniqueIndexes")]
    partial class SharedResourcePartialUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("UniEmu.Domain.Entities.CncProgramEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBinary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CncPrograms_Shared_Name")
                        .HasFilter("Scope = 'shared' AND EmulatorId IS NULL");

                    b.HasIndex("EmulatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CncPrograms_EmulatorId_Name")
                        .HasFilter("Scope = 'emulator' AND EmulatorId IS NOT NULL");

                    b.HasIndex("Scope", "EmulatorId", "Name")
                        .IsUnique();

                    b.ToTable("CncPrograms");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.EmulatorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextRun")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Emulators");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.EmulatorTagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalcJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("FormulaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundDigits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScenarioJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialParameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmulatorId");

                    b.ToTable("EmulatorTags");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.ScriptFileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ScriptFiles_Shared_Name")
                        .HasFilter("Scope = 'shared' AND EmulatorId IS NULL");

                    b.HasIndex("EmulatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ScriptFiles_EmulatorId_Name")
                        .HasFilter("Scope = 'emulator' AND EmulatorId IS NOT NULL");

                    b.HasIndex("Scope", "EmulatorId", "Name")
                        .IsUnique();

                    b.ToTable("ScriptFiles");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.ScriptRuntimeStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmulatorId", "ScriptKey")
                        .IsUnique();

                    b.ToTable("ScriptRuntimeStates");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.SystemEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmulatorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("SystemEvents");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.TelemetryPointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmulatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmulatorId", "Timestamp");

                    b.ToTable("TelemetryPoints");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.CncProgramEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.EmulatorTagEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", "Emulator")
                        .WithMany("Tags")
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emulator");
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.ScriptFileEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.ScriptRuntimeStateEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.SystemEventEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.TelemetryPointEntity", b =>
                {
                    b.HasOne("UniEmu.Domain.Entities.EmulatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EmulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniEmu.Domain.Entities.EmulatorEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
