import { formatCount, getRussianCountForm } from '@/utils/plural';

export const localization = {
  components: {
    changelogDialog: {
      title: 'История изменений UniEmu Web Console',
    },
    defaultErrorComponent: {},
    layout: {
      appLayout: {
        dashboardNavLabel: 'Главная',
        emulatorsNavLabel: 'Эмуляторы',
        cncStorageNavLabel: 'Хранилище УП',
        scriptsNavLabel: 'Скрипты',
        logsNavLabel: 'Логи системы',
        settingsNavLabel: 'Настройки',
        switchToLightThemeAriaLabel: 'Переключить на светлую тему',
        switchToDarkThemeAriaLabel: 'Переключить на тёмную тему',
        collapsedLightThemeTooltip: 'Светлая тема',
        collapsedDarkThemeTooltip: 'Тёмная тема',
        expandedLightThemeLabel: 'Светлая тема',
        expandedDarkThemeLabel: 'Тёмная тема',
        expandMenuAriaLabel: 'Развернуть меню',
        expandMenuTooltip: 'Развернуть меню',
        collapseMenuLabel: 'Свернуть меню',
        version: (p0: unknown) => `Версия ${p0}`,
        openChangelogSuffix: ' - открыть changelog',
        versionLabel: 'Версия',
        dashboardBreadcrumbLabel: 'Главная',
        emulatorsBreadcrumbLabel: 'Эмуляторы',
        cncStorageBreadcrumbLabel: 'Хранилище УП',
        scriptsBreadcrumbLabel: 'Скрипты',
        logsBreadcrumbLabel: 'Логи системы',
        settingsBreadcrumbLabel: 'Настройки',
        reloadButtonLabel: 'Перезагрузить',
        headerSettingsLabel: 'Настройки',
      },
    },
    monacoCsxEditor: {
      getTagValueDescription: 'Получить текущее значение тега эмулятора по имени.',
      setTagValueDescription: 'Установить значение тега. Триггерит обновление подписчиков.',
      logInfoDescription: 'Записать info-сообщение в журнал эмулятора.',
      logWarningDescription: 'Записать предупреждение.',
      logErrorDescription: 'Записать ошибку.',
      sleepDescription: 'Приостановить выполнение скрипта (мс).',
      serverNowDescription: 'Текущее серверное время.',
      randomDescription: 'Псевдослучайное число в диапазоне.',
      emulatorContextDescription: 'Контекст текущего эмулятора (Id, Name, Status, Tags).',
      httpGetDescription: 'Выполнить HTTP GET запрос.',
      loadCncProgramDescription: 'Загрузить УП ЧПУ для исполнения.',
      includeScriptDescription: 'Подключить другой .csx скрипт.',
      referenceAssemblyDescription: 'Подключить сборку .NET.',
      loadingLabel: 'Загрузка Monaco…',
    },
    pagePlaceholder: {
      title: 'Раздел в разработке',
      description:
        'Этот модуль появится в следующих итерациях. Начните с настройки эмуляторов - это даст контекст для остальных частей системы.',
    },
    statusBadge: {
      runningLabel: 'Работает',
      stoppedLabel: 'Остановлен',
      errorLabel: 'Ошибка',
      idleLabel: 'Простой',
    },
    timeAgo: {},
    ui: {
      accordion: {},
      alertDialog: {},
      alert: {},
      aspectRatio: {},
      avatar: {},
      badge: {},
      breadcrumb: {},
      button: {},
      calendar: {},
      card: {},
      carousel: {},
      checkbox: {},
      collapsible: {},
      command: {},
      contextMenu: {},
      dialog: {},
      drawer: {},
      dropdownMenu: {},
      form: {},
      hoverCard: {},
      inputOtp: {},
      input: {},
      label: {},
      menubar: {},
      navigationMenu: {},
      pagination: {},
      popover: {},
      progress: {},
      radioGroup: {},
      resizable: {},
      scrollArea: {},
      select: {},
      separator: {},
      sheet: {},
      sidebar: {},
      skeleton: {},
      slider: {},
      sonner: {},
      switch: {},
      table: {},
      tabs: {},
      textarea: {},
      toggleGroup: {},
      toggle: {},
      tooltip: {},
    },
  },
  hooks: {
    useMobile: {},
  },
  router: {},
  routes: {
    cnc: {
      components: {
        cncStoragePage: {
          title: 'Хранилище УП',
          description: 'Управляющие программы для ЧПУ-станков',
          filesCountLabel: (p0: number) => formatCount(p0, ['файл', 'файла', 'файлов']),
          uploadButtonLabel: 'Загрузить',
          searchPlaceholder: 'Найти программу…',
          sharedProgramsTitle: 'Общие программы',
          sharedProgramsDropHint: 'Перетащите файлы сюда или нажмите +',
          emulatorProgramsTitle: 'По эмуляторам',
          emptyEmulatorProgramsHint: 'Пусто - перетащите файл',
        },
        cncViewer: {
          dirtyBadgeLabel: 'изменено',
          updatedBadgeLabel: 'обновлено',
          downloadButtonLabel: 'Скачать',
          saveButtonLabel: 'Сохранить',
          editButtonLabel: 'Редактировать',
          descriptionLabel: 'Описание',
          descriptionPlaceholder: 'Краткое описание программы…',
          missingDescriptionText: '- описание не задано',
          binaryPreviewUnavailable: 'Бинарный файл - предпросмотр недоступен',
          downloadBinaryHint: 'Используйте «Скачать» для выгрузки',
          lineCountLabel: (p0: number) => formatCount(p0, ['строка', 'строки', 'строк']),
          loadedBadgeLabel: 'загружено',
        },
        dropZone: {
          title: 'Перетащите файлы УП сюда',
          separatorLabel: 'или',
          chooseFilesButtonLabel: 'Выбрать файлы',
          supportedFormatsHint: 'Поддерживаются .nc, .gcode, .tap, .mpf и другие текстовые форматы',
        },
        emptyHint: {},
        fileRow: {
          downloadActionLabel: 'Скачать',
          confirmDeleteMessage: (p0: string) => `Удалить "${p0}"?`,
          deleteActionLabel: 'Удалить',
        },
        treeGroup: {
          uploadToGroupTitle: 'Загрузить файл в группу',
        },
      },
      index: {
        title: 'UniEmu - Хранилище УП',
        description: 'Хранение управляющих программ ЧПУ (G-код) с группировкой по эмуляторам.',
      },
      utils: {
        index: {
          bytesLabel: (p0: number) => `${p0} Б`,
          kilobytesLabel: (p0: number) => `${p0} КБ`,
          megabytesLabel: (p0: number) => `${p0} МБ`,
        },
      },
    },
    components: {
      dashboardPage: {
        attentionSummary: (p0: unknown, p1: unknown) => `${p0} ${p1} внимания`,
        allSystemsHealthyLabel: 'Все системы в норме',
        allEmulatorsStoppedLabel: 'Все эмуляторы остановлены',
        title: 'Панель управления',
        description: 'Состояние парка виртуальных устройств в реальном времени',
        allEmulatorsButtonLabel: 'Все эмуляторы',
        newEmulatorButtonLabel: 'Новый эмулятор',
        fleetReadinessLabel: 'Готовность парка',
        activeCountLabel: (p0: number) => getRussianCountForm(p0, ['активен', 'активны', 'активны']),
        totalStatLabel: 'Всего',
        registeredHint: 'зарегистрировано',
        activeStatLabel: 'Активны',
        stoppedCountHint: (p0: number, _p1: number) => `${p0} остановлено`,
        errorsStatLabel: 'Ошибки',
        requiresAttentionHint: 'требует внимания',
        noErrorsHint: 'нет ошибок',
        totalRequestsStatLabel: 'Запросов всего',
        payloadTagsHint: (p0: number) => `${formatCount(p0, ['тег', 'тега', 'тегов'])} в payload`,
        statusDistributionTitle: 'Распределение по статусу',
        devicesCountLabel: (p0: number) => formatCount(p0, ['устройство', 'устройства', 'устройств']),
        emulatorsSectionTitle: 'Эмуляторы',
        emulatorsSectionDescription: 'Активные сверху · быстрый старт/стоп и переход в карточку',
        searchPlaceholder: 'Поиск по имени…',
        emptyFleetMessage: 'Ещё нет ни одного эмулятора. Создайте первый, чтобы начать.',
        emptySearchMessage: 'Ничего не найдено',
        eventsFeedTitle: 'Лента событий',
        latestEventsPrefix: 'Последние',
        eventsCountLabel: (p0: number) => formatCount(p0, ['запись', 'записи', 'записей']),
        singleEmulatorRequiresLabel: 'эмулятор требует',
        multipleEmulatorsRequireLabel: 'эмуляторов требуют',
        running: 'Запущено',
        idle: 'Простой',
        stopped: 'Остановлен',
        errors: 'Ошибки',
      },
      distributionBar: {},
      emulatorTile: {},
      statTile: {},
    },
    emulators: {
      id: {
        title: 'Эмулятор',
        notFoundTitle: 'Эмулятор не найден',
        backToListLabel: '← К списку',
      },
      components: {
        addTagDrawer: {
          amplitudeLabel: 'Амплитуда',
          centerLabel: 'Центр',
          finishLabel: 'Конечное значение',
          maxLabel: 'Максимум',
          minLabel: 'Минимум',
          startLabel: 'Начальное значение',
          curvatureLabel: 'Кривизна',
          parameterKeyLabel: 'Ключ параметра',
          specialParameterLabel: 'Специальный параметр',
          dataTypeLabel: 'Тип данных',
          programPickerSelectPlaceholder: 'Выберите УП',
          programPickerSearchPlaceholder: 'Найти УП...',
          programPickerEmpty: 'УП не найдены',
          programPickerCurrentGroup: 'Текущее значение',
          programPickerCurrentMissing: 'Нет в текущем списке УП',
          programPickerSharedGroup: 'Общие УП',
          programPickerEmulatorGroup: 'УП этого эмулятора',
          staticSourceLabel: 'Статическое значение',
          generatorSourceLabel: 'Генератор по формуле',
          scenarioSourceLabel: 'Сценарий по таймлайну',
          formulaScriptSourceLabel: 'Формула + скрипт',
          scriptSourceLabel: 'Пользовательский .csx-скрипт',
          cncSourceLabel: 'Значение из ЧПУ-контекста',
          cncPreviewLabel: '(из ЧПУ)',
          scenarioPreviewLabel: '(сценарий)',
          computedPreviewLabel: '(вычисляется)',
          editTitle: 'Редактировать тег',
          createTitle: 'Добавить тег',
          description: 'Параметры payload-а, который эмулятор отправит в SCADA-эндпоинт.',
          basicsSectionTitle: 'Базовые',
          tagNameLabel: 'Имя тега',
          tagNameHint: 'Отображаемое имя - для удобства в UI.',
          tagKeyHint: 'Ключ, который уходит в SCADA-payload.',
          optionalBadge: '(опционально)',
          specialParameterHint: 'Отдельное поле UniEmu protocol - не влияет на Name и Key.',
          roundDigitsLabel: 'Округлять до',
          digitsSuffixLabel: 'Знаков',
          valueSourceLabel: 'Источник значения',
          staticValueLabel: 'Статическое значение',
          descriptionLabel: 'Описание (опционально)',
          sendTagLabel: 'Отправлять тег',
          sendTagHint: 'Если выключено - тег не отправляется, но вычисляется',
          scenarioTimelineTitle: 'Сценарий - таймлайн',
          scenarioTimelineTriggerHint: 'Триггер: каждую секунду · по таймингу сегментов',
          triggerSectionTitle: 'Триггер вычисления',
          triggerModeOnceLabel: 'Единоразово (по событию)',
          triggerModeCronLabel: 'По CRON-выражению',
          triggerModeIntervalLabel: 'С периодичностью',
          triggerEventLabel: 'Событие',
          triggerEventOnStartLabel: 'При старте эмулятора',
          triggerEventOnStopLabel: 'При остановке эмулятора',
          cronExpressionLabel: 'CRON-выражение',
          cronExamplePrefix: 'Например: ',
          cronDailyMidnightHint: '- каждый день в полночь',
          intervalEveryLabel: 'Каждые',
          intervalUnitLabel: 'Единица',
          millisecondsUnitLabel: 'мс',
          secondsUnitLabel: 'сек',
          minutesUnitLabel: 'мин',
          calcFormulaTitle: 'формула расчёта',
          sequenceJsonLabel: 'Список (JSON)',
          durationSecondsLabel: 'Продолжительность (сек)',
          periodSecondsLabel: 'Период (сек)',
          distortionPercentLabel: 'Искажение (% шума)',
          scriptSectionTitle: 'Скрипт',
          existingScriptLabel: 'Существующий скрипт',
          customScriptDividerLabel: '- Кастомный скрипт ниже -',
          inlineScriptLabel: 'Inline-скрипт (.csx)',
          editScriptButtonLabel: 'Редактировать',
          cancelButtonLabel: 'Отмена',
          saveButtonLabel: 'Сохранить',
          createTagButtonLabel: 'Создать тег',
          inlineScriptEditorTitle: 'Редактор inline-скрипта',
          inlineScriptEditorDescription: 'C# Script (.csx) с подсветкой, автодополнением и host-API подсказками.',
          editorCancelButtonLabel: 'Отмена',
          applyScriptButtonLabel: 'Применить',
          confirmCloseTitle: 'Закрыть без сохранения?',
          confirmCloseDescription: 'В теге есть несохраненные изменения. Если закрыть редактор, они будут потеряны.',
          stayButtonLabel: 'Остаться',
          closeButtonLabel: 'Закрыть',
          confirmScriptEditorCloseTitle: 'Закрыть редактор скрипта?',
          confirmScriptEditorCloseDescription:
            'В inline-скрипте есть непримененные изменения. Если закрыть редактор, они будут потеряны.',
          scriptEditorStayButtonLabel: 'Остаться',
          scriptEditorCloseButtonLabel: 'Закрыть',
        },
        editEmulatorDrawer: {
          nameRequiredMessage: 'Имя обязательно',
          protocolIdMinMessage: 'Id протокола должен быть ≥ 1',
          targetUrlRequiredMessage: 'URL обязателен',
          targetUrlInvalidMessage: 'Некорректный URL',
          intervalMinMessage: 'Интервал должен быть ≥ 1 сек',
          editTitle: 'Изменить конфигурацию',
          emulatorTitle: (p0: unknown) => `Эмулятор ${p0}`,
          nameLabel: 'Имя эмулятора',
          protocolIdHint: 'Числовой идентификатор протокола',
          targetUrlLabel: 'Целевой URL',
          targetUrlHint: 'Endpoint, куда отправляются пакеты телеметрии',
          sendIntervalLabel: 'Интервал отправки (сек)',
          tagsCountLabel: 'Тегов',
          cancelButtonLabel: 'Отмена',
          saveButtonLabel: 'Сохранить',
          confirmCloseTitle: 'Закрыть без сохранения?',
          confirmCloseDescription:
            'В конфигурации есть несохраненные изменения. Если закрыть редактор, они будут потеряны.',
          stayButtonLabel: 'Остаться',
          closeButtonLabel: 'Закрыть',
          protocolIdLabel: 'ID протокола',
        },
        emulatorDetailPage: {
          downloadDispatcherTemplate: 'Шаблон XML',
          resume: 'Возобновить',
          pause: 'Пауза',
          keyColumnLabel: 'Ключ',
          calcColumnLabel: 'Расчёт',
          timelineTriggerLabel: 'по таймлайну',
          onStopTriggerLabel: 'при остановке',
          onStartTriggerLabel: 'при старте',
          intervalTriggerLabel: (p0: unknown, p1: unknown) => `каждые ${p0} ${p1}`,
          overviewTabLabel: 'Общее',
          tagsTabLabel: 'Теги',
          monitoringTabLabel: 'Мониторинг',
          logsTabLabel: 'Логи',
          telemetryTimeSeriesTitle: 'Телеметрия - временной ряд',
          backToListLabel: 'К списку эмуляторов',
          runOnceButtonLabel: 'Запустить однократно',
          stopButtonLabel: 'Стоп',
          startButtonLabel: 'Старт',
          deleteEmulatorButtonLabel: 'Удалить эмулятор',
          deleteButtonLabel: 'Удалить',
          deleteDialogTitle: 'Удалить эмулятор?',
          deleteDialogSubjectLabel: 'Эмулятор',
          deleteDialogDescriptionSuffix:
            'будет удалён вместе со всеми тегами, телеметрией и связанными событиями. Действие необратимо.',
          cancelButtonLabel: 'Отмена',
          confirmDeleteButtonLabel: 'Удалить',
          configurationTitle: 'Конфигурация',
          targetUrlLabel: 'Целевой URL',
          intervalLabel: 'Интервал',
          secondsUnitLabel: 'сек',
          emulatorIdLabel: 'ID эмулятора',
          payloadTagsLabel: 'Тегов в payload',
          editConfigurationButtonLabel: 'Изменить конфигурацию',
          uptimeLabel: 'Аптайм',
          totalRequestsLabel: 'Всего запросов',
          lastRunLabel: 'Последний запуск',
          scenarioSummary: (p0: number, p1: number, p2: number) => `сценарий · ${p0} сегм · Σ ${p1} · ${p2}`,
          sendTagTitle: 'Отправлять тег',
          editTagTitle: 'Редактировать тег',
          deleteTagTitle: 'Удалить тег',
          nameColumnLabel: 'Имя',
          typeColumnLabel: 'Тип',
          sourceColumnLabel: 'Источник',
          triggerColumnLabel: 'Триггер',
          previewColumnLabel: 'Предпросмотр',
          enabledTagsSectionTitle: 'Отправляемые теги',
          enabledTagsSectionDescription: 'Вычисляются и отправляются в систему',
          tagsCountLabel: (p0: number) => formatCount(p0, ['тег', 'тега', 'тегов']),
          addTagButtonLabel: 'Добавить тег',
          emptyEnabledTagsMessage: 'Нет отправляемых тегов',
          disabledTagsSectionTitle: 'Не отправляемые теги',
          disabledTagsSectionDescription: 'Вычисляются, но не отправляются в систему',
          emptyDisabledTagsMessage: 'Нет отключённых тегов',
          chartHoverHint: 'наведите курсор на график',
          tagValuesTitle: 'Значения тегов',
          cursorSnapshotLabel: 'снимок по курсору',
          latestSnapshotLabel: 'последний снимок',
          tagColumnLabel: 'Тег',
          valueTypeColumnLabel: 'Тип',
          valueColumnLabel: 'Значение',
          emptyTagsMessage: 'Нет тегов',
          tagScenariosTitle: 'Сценарии тегов',
          tagScenariosDescription: 'Профиль значений по таймлайну · красная линия - позиция курсора графика',
          segmentsSumLabel: 'сегм · Σ',
          packetHistoryTitle: 'История пакетов',
          packetHistorySummary: (p0: number, p1: number) =>
            `Сохраняется ${formatCount(p0, ['последний пакет', 'последних пакета', 'последних пакетов'])}, показано ${p1}`,
          latestPacketLabel: 'последний',
          eventsLogTitle: 'Журнал событий',
          eventsCountLabel: (p0: number) => formatCount(p0, ['запись', 'записи', 'записей']),
          emptyEventsMessage: 'Событий по этому эмулятору пока нет',
          secondsShortLabel: 'сек',
          protocolIdLabel: 'ID протокола',
        },
        emulatorsListPage: {
          allFilterLabel: 'Все',
          runningFilterLabel: 'Работают',
          stoppedFilterLabel: 'Остановлены',
          errorsFilterLabel: 'Ошибки',
          title: 'Эмуляторы',
          description: 'Управление виртуальными устройствами и их конфигурацией',
          createButtonLabel: 'Создать эмулятор',
          searchPlaceholder: 'Поиск по имени…',
          tagsCountLabel: 'Тегов',
          uptimeLabel: 'Аптайм',
          requestsCountLabel: 'Запросов',
          lastRunPrefix: 'Последний: ',
          emptySearchMessage: 'Ничего не найдено',
          newEmulatorTitle: 'Новый эмулятор',
          newEmulatorDescription: 'Создайте виртуальное устройство. Запустить его можно будет позже.',
          nameLabel: 'Имя',
          targetUrlLabel: 'Целевой URL',
          sendIntervalLabel: 'Интервал отправки (сек)',
          cancelButtonLabel: 'Отмена',
          createButtonText: 'Создать',
          protocolIdLabel: 'ID протокола',
        },
        tagScenario: {
          calcConfigFields: {
            sequenceJsonLabel: 'Список (JSON)',
            periodSecondsLabel: 'Период (с)',
            durationSecondsLabel: 'Продолжительность (сек)',
            distortionPercentLabel: 'Искажение (% шума)',
          },
          scenarioEditor: {
            segmentsCountLabel: (p0: number) => formatCount(p0, ['сегмент', 'сегмента', 'сегментов']),
            endBehaviorLabel: 'По завершении',
            endBehaviorNoSignalLabel: 'Без сигнала',
            endBehaviorZeroLabel: 'Обнулить',
            endBehaviorRepeatLabel: 'Повторять',
            endBehaviorHoldLabel: 'Удерживать',
            searchPlaceholder: 'Поиск по метке или типу…',
            collapseAllButtonLabel: 'Свернуть всё',
            expandAllButtonLabel: 'Раскрыть всё',
            collapseAllTooltip: 'Свернуть всё',
            expandAllTooltip: 'Раскрыть всё',
            addSegmentButtonLabel: 'Добавить',
            emptySearchMessage: 'Ничего не найдено',
            missingLabelText: 'без метки',
            moveUpButtonLabel: 'Вверх',
            moveDownButtonLabel: 'Вниз',
            duplicateButtonLabel: 'Дублировать',
            deleteButtonLabel: 'Удалить',
            duplicateMenuLabel: 'Дублировать',
            moveUpMenuLabel: 'Вверх',
            moveDownMenuLabel: 'Вниз',
            deleteMenuLabel: 'Удалить',
            labelFieldLabel: 'Метка',
            labelPlaceholder: 'Разгон…',
            durationLabel: 'Длительность',
            durationUnitLabel: 'Единица',
            secondsUnitLabel: 'сек',
            minutesUnitLabel: 'мин',
            emptyTimelineMessage: 'Добавьте первый сегмент, чтобы начать',
          },
          scenarioPreviewChart: {
            emptyPreviewMessage: 'Добавьте сегменты, чтобы увидеть превью',
          },
        },
      },
      index: {
        title: 'UniEmu - Эмуляторы',
        description: 'Список эмуляторов и управление ими.',
      },
    },
    index: {
      title: 'UniEmu - Главная',
      description: 'Панель управления эмуляторами UniEmu.',
    },
    logs: {
      components: {
        logsPage: {
          title: 'Логи системы',
          description: 'Журналы бэкенда и системные события',
        },
      },
      index: {
        title: 'UniEmu - Логи',
      },
    },
    scripts: {
      components: {
        createScriptModal: {
          title: 'Новый скрипт',
          descriptionPrefix: 'Файлы C# (.csx) хранятся в репозитории и могут подключаться через',
          scopeLabel: 'Область',
          sharedScopeLabel: 'Общий',
          emulatorScopeLabel: 'Эмулятора',
          emulatorLabel: 'Эмулятор',
          fileNameLabel: 'Имя файла',
          fileNamePlaceholder: 'например, spindle.csx',
          extensionLabel: 'Расширение',
          extensionHint: 'добавится автоматически.',
          cancelButtonLabel: 'Отмена',
          createButtonLabel: 'Создать',
        },
        emptyHint: {},
        fileRow: {
          confirmDeleteMessage: (p0: string) => `Удалить "${p0}"?`,
          deleteActionLabel: 'Удалить',
        },
        scriptEditor: {
          dirtyBadgeLabel: 'изменено',
          kilobytesUnitLabel: 'КБ',
          updatedBadgeLabel: 'обновлено',
          saveButtonLabel: 'Сохранить',
          sharedScopeHint: 'доступен всем эмуляторам',
          saveErrorMessage: 'Не удалось сохранить скрипт',
          editButtonLabel: 'Редактировать',
        },
        scriptsPage: {
          title: 'Скрипты',
          description: 'Хранилище C# скриптов (.csx)',
          filesCountLabel: (p0: number) => formatCount(p0, ['файл', 'файла', 'файлов']),
          kilobytesUnitLabel: 'КБ',
          newScriptButtonLabel: 'Новый скрипт',
          searchPlaceholder: 'Найти файл…',
          sharedScriptsTitle: 'Общие скрипты',
          emptySharedScriptsMessage: 'Нет общих скриптов',
          emulatorScriptsTitle: 'По эмуляторам',
          emptyEmulatorScriptsMessage: 'Пусто',
          emptySelectionMessage: 'Выберите файл из дерева слева или создайте новый',
        },
        treeGroup: {
          addFileToGroupTitle: 'Добавить файл в группу',
        },
      },
      index: {
        title: 'UniEmu - Скрипты',
        description: 'Хранилище C# (.csx) скриптов с группировкой по эмуляторам.',
      },
    },
    settings: {
      components: {
        settingsPage: {
          title: 'Настройки',
          description: 'Глобальные параметры приложения',
          telemetrySectionTitle: 'Телеметрия',
          telemetryHistoryDescription: 'История отправленных пакетов, доступная во вкладке мониторинга',
          packetHistoryLimitLabel: 'Сохранять последних пакетов',
          packetHistoryLimitHint: 'Диапазон: 1–1000. Старые пакеты удаляются автоматически.',
        },
      },
      index: {
        title: 'UniEmu - Настройки',
      },
    },
    root: {
      description: 'Панель управления эмуляторами протокола Universal.',
      metaDescription: 'Панель управления эмуляторами протокола Universal.',
      fallbackDescription: 'Панель управления эмуляторами протокола Universal.',
    },
  },
} as const;
