/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as EmulatorsIndexRouteImport } from './routes/emulators/index'
import { Route as CncIndexRouteImport } from './routes/cnc/index'
import { Route as EmulatorsIdRouteImport } from './routes/emulators/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmulatorsIndexRoute = EmulatorsIndexRouteImport.update({
  id: '/emulators/',
  path: '/emulators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CncIndexRoute = CncIndexRouteImport.update({
  id: '/cnc/',
  path: '/cnc/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmulatorsIdRoute = EmulatorsIdRouteImport.update({
  id: '/emulators/$id',
  path: '/emulators/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emulators/$id': typeof EmulatorsIdRoute
  '/cnc/': typeof CncIndexRoute
  '/emulators/': typeof EmulatorsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emulators/$id': typeof EmulatorsIdRoute
  '/cnc': typeof CncIndexRoute
  '/emulators': typeof EmulatorsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emulators/$id': typeof EmulatorsIdRoute
  '/cnc/': typeof CncIndexRoute
  '/emulators/': typeof EmulatorsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emulators/$id'
    | '/cnc/'
    | '/emulators/'
    | '/logs/'
    | '/scripts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emulators/$id'
    | '/cnc'
    | '/emulators'
    | '/logs'
    | '/scripts'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/emulators/$id'
    | '/cnc/'
    | '/emulators/'
    | '/logs/'
    | '/scripts/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmulatorsIdRoute: typeof EmulatorsIdRoute
  CncIndexRoute: typeof CncIndexRoute
  EmulatorsIndexRoute: typeof EmulatorsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emulators/': {
      id: '/emulators/'
      path: '/emulators'
      fullPath: '/emulators/'
      preLoaderRoute: typeof EmulatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnc/': {
      id: '/cnc/'
      path: '/cnc'
      fullPath: '/cnc/'
      preLoaderRoute: typeof CncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emulators/$id': {
      id: '/emulators/$id'
      path: '/emulators/$id'
      fullPath: '/emulators/$id'
      preLoaderRoute: typeof EmulatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmulatorsIdRoute: EmulatorsIdRoute,
  CncIndexRoute: CncIndexRoute,
  EmulatorsIndexRoute: EmulatorsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
